#!/bin/sh

# Create directories
mkdir -p /etc/socks-clash/config
mkdir -p /etc/socks-clash/core

# Set permissions
chmod 755 /etc/init.d/socks-clash
chmod 755 /usr/share/socks-clash/*.sh 2>/dev/null

# Enable service
/etc/init.d/socks-clash enable

exit 0
