#!/bin/bash
# SocksClash Configuration Generator

CONFIG_DIR="/etc/socks-clash/config"
CONFIG_FILE="$CONFIG_DIR/config.yaml"
UCI_CONFIG="socks-clash"

# Load UCI settings
load_config() {
    enable=$(uci -q get $UCI_CONFIG.config.enable)
    socks_port=$(uci -q get $UCI_CONFIG.config.socks_port || echo "7891")
    http_port=$(uci -q get $UCI_CONFIG.config.http_port || echo "7890")
    mixed_port=$(uci -q get $UCI_CONFIG.config.mixed_port || echo "7893")
    cn_port=$(uci -q get $UCI_CONFIG.config.cn_port || echo "9090")
    log_level=$(uci -q get $UCI_CONFIG.config.log_level || echo "info")
    mode=$(uci -q get $UCI_CONFIG.config.mode || echo "rule")
    allow_lan=$(uci -q get $UCI_CONFIG.config.allow_lan || echo "1")
    bind_address=$(uci -q get $UCI_CONFIG.config.bind_address || echo "*")
    ipv6=$(uci -q get $UCI_CONFIG.config.ipv6 || echo "0")
    dashboard_password=$(uci -q get $UCI_CONFIG.config.dashboard_password || echo "")
    socks_enabled=$(uci -q get $UCI_CONFIG.config.socks_enabled || echo "1")
    http_enabled=$(uci -q get $UCI_CONFIG.config.http_enabled || echo "1")
    mixed_enabled=$(uci -q get $UCI_CONFIG.config.mixed_enabled || echo "0")
}

# Generate YAML config
generate_config() {
    mkdir -p "$CONFIG_DIR"
    
    cat > "$CONFIG_FILE" <<EOF
# SocksClash Configuration
# Auto-generated by socks-clash - $(date)

# Port configuration
EOF

    if [ "$mixed_enabled" = "1" ]; then
        echo "mixed-port: $mixed_port" >> "$CONFIG_FILE"
    fi
    
    if [ "$http_enabled" = "1" ]; then
        echo "port: $http_port" >> "$CONFIG_FILE"
    fi
    
    if [ "$socks_enabled" = "1" ]; then
        echo "socks-port: $socks_port" >> "$CONFIG_FILE"
    fi

    cat >> "$CONFIG_FILE" <<EOF

# LAN access
allow-lan: $([ "$allow_lan" = "1" ] && echo "true" || echo "false")
bind-address: "$bind_address"

# Mode and logging
mode: $mode
log-level: $log_level
ipv6: $([ "$ipv6" = "1" ] && echo "true" || echo "false")

# External controller
external-controller: 0.0.0.0:$cn_port
EOF

    if [ -n "$dashboard_password" ]; then
        echo "secret: \"$dashboard_password\"" >> "$CONFIG_FILE"
    fi

    cat >> "$CONFIG_FILE" <<EOF

# Profile settings
profile:
  store-selected: true
  store-fake-ip: false

# DNS (disabled for proxy-only mode)
dns:
  enable: false

# Proxies
proxies: []

# Proxy Groups
proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - DIRECT
      - REJECT

# Rules
rules:
EOF

    # Add custom rules from UCI
    uci -q show $UCI_CONFIG | grep "custom_rule" | while read -r line; do
        if echo "$line" | grep -q "type="; then
            section=$(echo "$line" | cut -d'.' -f2)
            rule_enabled=$(uci -q get "$UCI_CONFIG.$section.enabled")
            if [ "$rule_enabled" = "1" ]; then
                rule_type=$(uci -q get "$UCI_CONFIG.$section.type")
                rule_value=$(uci -q get "$UCI_CONFIG.$section.value")
                rule_action=$(uci -q get "$UCI_CONFIG.$section.action")
                if [ -n "$rule_type" ] && [ -n "$rule_value" ] && [ -n "$rule_action" ]; then
                    echo "  - $rule_type,$rule_value,$rule_action" >> "$CONFIG_FILE"
                fi
            fi
        fi
    done

    # Add default rules
    geoip_cn=$(uci -q get $UCI_CONFIG.config.geoip_cn_direct || echo "1")
    private_direct=$(uci -q get $UCI_CONFIG.config.private_direct || echo "1")
    final_rule=$(uci -q get $UCI_CONFIG.config.final_rule || echo "PROXY")
    
    if [ "$private_direct" = "1" ]; then
        echo "  - IP-CIDR,192.168.0.0/16,DIRECT" >> "$CONFIG_FILE"
        echo "  - IP-CIDR,10.0.0.0/8,DIRECT" >> "$CONFIG_FILE"
        echo "  - IP-CIDR,172.16.0.0/12,DIRECT" >> "$CONFIG_FILE"
        echo "  - IP-CIDR,127.0.0.0/8,DIRECT" >> "$CONFIG_FILE"
    fi
    
    if [ "$geoip_cn" = "1" ]; then
        echo "  - GEOIP,CN,DIRECT" >> "$CONFIG_FILE"
    fi
    
    echo "  - MATCH,$final_rule" >> "$CONFIG_FILE"
    
    echo "$(date '+%Y-%m-%d %H:%M:%S') Configuration generated: $CONFIG_FILE" >> /tmp/socks-clash.log
}

# Main
load_config
generate_config
